/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISUAL;


import Logica.MainFrame;
import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author darwi
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnsalir = new javax.swing.JButton();
        panel_1 = new javax.swing.JPanel();
        btnejericicio1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        panel_3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnejericicio3 = new javax.swing.JButton();
        panel_4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnejericicio2 = new javax.swing.JButton();
        panel_5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnejericicio4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 19));

        jPanel2.setBackground(new java.awt.Color(0, 40, 58));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PC4_ANALISIS");

        btnsalir.setBackground(new java.awt.Color(0, 0, 0));
        btnsalir.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnsalir.setForeground(new java.awt.Color(0, 255, 51));
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/SALIR_COLOR.png"))); // NOI18N
        btnsalir.setText("SALIR");
        btnsalir.setAutoscrolls(true);
        btnsalir.setFocusCycleRoot(true);
        btnsalir.setFocusPainted(false);
        btnsalir.setFocusable(false);
        btnsalir.setInheritsPopupMenu(true);
        btnsalir.setRequestFocusEnabled(false);
        btnsalir.setRolloverEnabled(false);
        btnsalir.setVerifyInputWhenFocusTarget(false);
        btnsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsalirMouseExited(evt);
            }
        });
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(264, 264, 264)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(320, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        panel_1.setBackground(new java.awt.Color(0, 40, 60));
        panel_1.setForeground(new java.awt.Color(0, 255, 0));
        panel_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_1MouseExited(evt);
            }
        });

        btnejericicio1.setBackground(new java.awt.Color(0, 0, 0));
        btnejericicio1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnejericicio1.setForeground(new java.awt.Color(0, 255, 51));
        btnejericicio1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/SETTINGS.png"))); // NOI18N
        btnejericicio1.setText("EJERCICIO 1");
        btnejericicio1.setAutoscrolls(true);
        btnejericicio1.setFocusCycleRoot(true);
        btnejericicio1.setFocusPainted(false);
        btnejericicio1.setFocusable(false);
        btnejericicio1.setInheritsPopupMenu(true);
        btnejericicio1.setRequestFocusEnabled(false);
        btnejericicio1.setRolloverEnabled(false);
        btnejericicio1.setVerifyInputWhenFocusTarget(false);
        btnejericicio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnejericicio1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnejericicio1MouseExited(evt);
            }
        });
        btnejericicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnejericicio1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 51));
        jLabel2.setText("GRAFOS NO DIRIGIDOS");

        javax.swing.GroupLayout panel_1Layout = new javax.swing.GroupLayout(panel_1);
        panel_1.setLayout(panel_1Layout);
        panel_1Layout.setHorizontalGroup(
            panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(33, 33, 33))
            .addGroup(panel_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnejericicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_1Layout.setVerticalGroup(
            panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnejericicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_3.setBackground(new java.awt.Color(0, 40, 60));
        panel_3.setForeground(new java.awt.Color(0, 255, 0));
        panel_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_3MouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 51));
        jLabel3.setText("GRAFOS NO DIRIGIDOS");

        btnejericicio3.setBackground(new java.awt.Color(0, 0, 0));
        btnejericicio3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnejericicio3.setForeground(new java.awt.Color(0, 255, 51));
        btnejericicio3.setText("EJERCICIO 3");
        btnejericicio3.setAutoscrolls(true);
        btnejericicio3.setFocusCycleRoot(true);
        btnejericicio3.setFocusPainted(false);
        btnejericicio3.setFocusable(false);
        btnejericicio3.setInheritsPopupMenu(true);
        btnejericicio3.setRequestFocusEnabled(false);
        btnejericicio3.setRolloverEnabled(false);
        btnejericicio3.setVerifyInputWhenFocusTarget(false);
        btnejericicio3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnejericicio3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnejericicio3MouseExited(evt);
            }
        });
        btnejericicio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnejericicio3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_3Layout = new javax.swing.GroupLayout(panel_3);
        panel_3.setLayout(panel_3Layout);
        panel_3Layout.setHorizontalGroup(
            panel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(btnejericicio3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panel_3Layout.setVerticalGroup(
            panel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnejericicio3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(257, 257, 257))
        );

        panel_4.setBackground(new java.awt.Color(0, 40, 60));
        panel_4.setForeground(new java.awt.Color(0, 255, 0));
        panel_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_4MouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 51));
        jLabel5.setText("GRAFOS NO DIRIGIDOS");

        btnejericicio2.setBackground(new java.awt.Color(0, 0, 0));
        btnejericicio2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnejericicio2.setForeground(new java.awt.Color(0, 255, 51));
        btnejericicio2.setText("EJERCICIO 2");
        btnejericicio2.setAutoscrolls(true);
        btnejericicio2.setFocusCycleRoot(true);
        btnejericicio2.setFocusPainted(false);
        btnejericicio2.setFocusable(false);
        btnejericicio2.setInheritsPopupMenu(true);
        btnejericicio2.setRequestFocusEnabled(false);
        btnejericicio2.setRolloverEnabled(false);
        btnejericicio2.setVerifyInputWhenFocusTarget(false);
        btnejericicio2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnejericicio2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnejericicio2MouseExited(evt);
            }
        });
        btnejericicio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnejericicio2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_4Layout = new javax.swing.GroupLayout(panel_4);
        panel_4.setLayout(panel_4Layout);
        panel_4Layout.setHorizontalGroup(
            panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_4Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(btnejericicio2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        panel_4Layout.setVerticalGroup(
            panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnejericicio2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(257, 257, 257))
        );

        panel_5.setBackground(new java.awt.Color(0, 40, 60));
        panel_5.setForeground(new java.awt.Color(0, 255, 0));
        panel_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_5MouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 51));
        jLabel6.setText("GRAFO VALORADO");

        btnejericicio4.setBackground(new java.awt.Color(0, 0, 0));
        btnejericicio4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnejericicio4.setForeground(new java.awt.Color(0, 255, 51));
        btnejericicio4.setText("EJERCICIO 4");
        btnejericicio4.setAutoscrolls(true);
        btnejericicio4.setFocusCycleRoot(true);
        btnejericicio4.setFocusPainted(false);
        btnejericicio4.setFocusable(false);
        btnejericicio4.setInheritsPopupMenu(true);
        btnejericicio4.setRequestFocusEnabled(false);
        btnejericicio4.setRolloverEnabled(false);
        btnejericicio4.setVerifyInputWhenFocusTarget(false);
        btnejericicio4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnejericicio4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnejericicio4MouseExited(evt);
            }
        });
        btnejericicio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnejericicio4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_5Layout = new javax.swing.GroupLayout(panel_5);
        panel_5.setLayout(panel_5Layout);
        panel_5Layout.setHorizontalGroup(
            panel_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_5Layout.createSequentialGroup()
                .addGroup(panel_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_5Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel6))
                    .addGroup(panel_5Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnejericicio4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        panel_5Layout.setVerticalGroup(
            panel_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnejericicio4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panel_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(panel_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(panel_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panel_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1125, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnejericicio1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnejericicio1MouseExited
        // TODO add your handling code here:
         btnejericicio1.setBorder(
            BorderFactory.createLineBorder(
                new Color(200,220,220),2
            )
        );
    }//GEN-LAST:event_btnejericicio1MouseExited

    private void btnejericicio1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnejericicio1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnejericicio1MouseEntered

    private void btnejericicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnejericicio1ActionPerformed
        // TODO add your handling code here:
        PREGUNTA1  p = new PREGUNTA1();
          p.setVisible(true);
        p.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnejericicio1ActionPerformed

    private void panel_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_1MouseExited
        // TODO add your handling code here:
         panel_1.setBorder(
            BorderFactory.createLineBorder(
                new Color(200,220,220),2
            )
        );
    }//GEN-LAST:event_panel_1MouseExited

    private void panel_1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_1MouseEntered

    private void btnejericicio3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnejericicio3MouseEntered
        // TODO add your handling code here:
          btnejericicio3.setBorder(
            BorderFactory.createLineBorder(
                new Color(200,220,220),2
            )
        );
        
    }//GEN-LAST:event_btnejericicio3MouseEntered

    private void btnejericicio3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnejericicio3MouseExited
        // TODO add your handling code here:
          
    }//GEN-LAST:event_btnejericicio3MouseExited

    private void btnejericicio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnejericicio3ActionPerformed
        // TODO add your handling code here:
       MainFrame  p = new MainFrame();
          p.setVisible(true);
        p.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_btnejericicio3ActionPerformed

    private void panel_3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_3MouseEntered
        // TODO add your handling code here:
        panel_3.setBorder(
            BorderFactory.createLineBorder(
                new Color(200,220,220),2
            )
        );
    }//GEN-LAST:event_panel_3MouseEntered

    private void panel_3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_3MouseExited

    private void btnsalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalirMouseEntered
        // TODO add your handling code here:
          btnsalir.setBorder(
            BorderFactory.createLineBorder(
                new Color(200,220,220),2
            )
        );
    }//GEN-LAST:event_btnsalirMouseEntered

    private void btnsalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalirMouseExited
        // TODO add your handling code here:
         btnsalir.setBorder(
            BorderFactory.createLineBorder(
                new Color(200,220,220),2
            )
        );
    }//GEN-LAST:event_btnsalirMouseExited

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnejericicio2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnejericicio2MouseEntered
        // TODO add your handling code here:
          btnejericicio2.setBorder(
            BorderFactory.createLineBorder(
                new Color(200,220,220),2
            )
        );
    }//GEN-LAST:event_btnejericicio2MouseEntered

    private void btnejericicio2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnejericicio2MouseExited
        // TODO add your handling code here:
         btnejericicio2.setBorder(
            BorderFactory.createLineBorder(
                new Color(200,220,220),2
            )
        );
         
    }//GEN-LAST:event_btnejericicio2MouseExited

    private void btnejericicio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnejericicio2ActionPerformed
        // TODO add your handling code here:
       PREGUNTA2  p = new PREGUNTA2();
          p.setVisible(true);
        p.setLocationRelativeTo(null);
        this.dispose();
      
        
    }//GEN-LAST:event_btnejericicio2ActionPerformed

    private void panel_4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_4MouseEntered

    private void panel_4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_4MouseExited
        // TODO add your handling code here:
           panel_4.setBorder(
            BorderFactory.createLineBorder(
                new Color(200,220,220),2
            )
        );
    }//GEN-LAST:event_panel_4MouseExited

    private void btnejericicio4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnejericicio4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnejericicio4MouseEntered

    private void btnejericicio4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnejericicio4MouseExited
        // TODO add your handling code here:
           panel_3.setBorder(
            BorderFactory.createLineBorder(
                new Color(200,220,220),2
            )
        );
    }//GEN-LAST:event_btnejericicio4MouseExited

    private void btnejericicio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnejericicio4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnejericicio4ActionPerformed

    private void panel_5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_5MouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_panel_5MouseEntered

    private void panel_5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_5MouseExited
        // TODO add your handling code here:
           panel_5.setBorder(
            BorderFactory.createLineBorder(
                new Color(200,220,220),2
            )
        );
    }//GEN-LAST:event_panel_5MouseExited

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnejericicio1;
    private javax.swing.JButton btnejericicio2;
    private javax.swing.JButton btnejericicio3;
    private javax.swing.JButton btnejericicio4;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JPanel panel_1;
    private javax.swing.JPanel panel_3;
    private javax.swing.JPanel panel_4;
    private javax.swing.JPanel panel_5;
    // End of variables declaration//GEN-END:variables
}
