/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISUAL;
import Logica.Numero;
import Logica.ListaNumeros;
import Logica.Quicksort;
import Logica.Shellsort;
import java.io.File;
import Logica.Txt_utp;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.Image;
import java.awt.Color;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author darwi
 */
public class PREGUNTA1 extends javax.swing.JFrame {
private ListaNumeros lista = new ListaNumeros();
    /**
     * Creates new form PRINCIPAL
     */
    public PREGUNTA1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pre1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btncargar = new javax.swing.JButton();
        btnresolver = new javax.swing.JButton();
        btnmenu = new javax.swing.JButton();
        btnlimpiar1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pre2 = new javax.swing.JPanel();
        txtarchivo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rbtshell = new javax.swing.JRadioButton();
        rtbquic = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtresultado = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaoriginal = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaordenado = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pre1.setBackground(new java.awt.Color(0, 0, 18));
        pre1.setForeground(new java.awt.Color(102, 102, 102));
        pre1.setPreferredSize(new java.awt.Dimension(945, 670));

        jPanel1.setBackground(new java.awt.Color(0, 40, 57));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncargar.setBackground(new java.awt.Color(0, 0, 0));
        btncargar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btncargar.setForeground(new java.awt.Color(51, 255, 51));
        btncargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/CARPETA_1.png"))); // NOI18N
        btncargar.setText("CARGAR");
        btncargar.setAutoscrolls(true);
        btncargar.setContentAreaFilled(false);
        btncargar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btncargar.setDoubleBuffered(true);
        btncargar.setFocusCycleRoot(true);
        btncargar.setFocusPainted(false);
        btncargar.setFocusable(false);
        btncargar.setVerifyInputWhenFocusTarget(false);
        btncargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncargarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncargarMouseExited(evt);
            }
        });
        btncargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncargarbtnpregun1ActionPerformed(evt);
            }
        });
        jPanel1.add(btncargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 163, 50));

        btnresolver.setBackground(new java.awt.Color(0, 0, 0));
        btnresolver.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnresolver.setForeground(new java.awt.Color(0, 255, 51));
        btnresolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/PLAY_COLOR.png"))); // NOI18N
        btnresolver.setText("ORDENAR");
        btnresolver.setAutoscrolls(true);
        btnresolver.setContentAreaFilled(false);
        btnresolver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnresolver.setDefaultCapable(false);
        btnresolver.setFocusPainted(false);
        btnresolver.setFocusable(false);
        btnresolver.setRequestFocusEnabled(false);
        btnresolver.setRolloverEnabled(false);
        btnresolver.setVerifyInputWhenFocusTarget(false);
        btnresolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnresolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnresolverMouseExited(evt);
            }
        });
        btnresolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresolverbtnpregun1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnresolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 200, 50));

        btnmenu.setBackground(new java.awt.Color(0, 0, 0));
        btnmenu.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        btnmenu.setForeground(new java.awt.Color(0, 255, 0));
        btnmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/MENUU_COLORR.png"))); // NOI18N
        btnmenu.setText("MENU");
        btnmenu.setAutoscrolls(true);
        btnmenu.setContentAreaFilled(false);
        btnmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnmenu.setDoubleBuffered(true);
        btnmenu.setFocusCycleRoot(true);
        btnmenu.setFocusPainted(false);
        btnmenu.setFocusable(false);
        btnmenu.setVerifyInputWhenFocusTarget(false);
        btnmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnmenuMouseExited(evt);
            }
        });
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 170, 50));

        btnlimpiar1.setBackground(new java.awt.Color(0, 0, 0));
        btnlimpiar1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnlimpiar1.setForeground(new java.awt.Color(51, 255, 51));
        btnlimpiar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/LIMPIAR_ORIGINAL_COLOR.png"))); // NOI18N
        btnlimpiar1.setText("LIMPIAR");
        btnlimpiar1.setAutoscrolls(true);
        btnlimpiar1.setContentAreaFilled(false);
        btnlimpiar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnlimpiar1.setDoubleBuffered(true);
        btnlimpiar1.setFocusCycleRoot(true);
        btnlimpiar1.setFocusPainted(false);
        btnlimpiar1.setFocusable(false);
        btnlimpiar1.setVerifyInputWhenFocusTarget(false);
        btnlimpiar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlimpiar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlimpiar1MouseExited(evt);
            }
        });
        btnlimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiar1btnpregun1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnlimpiar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 190, 50));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ORDENACION");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(326, 326, 326))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pre2.setBackground(java.awt.SystemColor.activeCaption);
        pre2.setForeground(new java.awt.Color(102, 102, 102));

        txtarchivo.setEditable(false);
        txtarchivo.setBackground(new java.awt.Color(0, 0, 0));
        txtarchivo.setForeground(new java.awt.Color(0, 255, 0));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("ARCHIVO:");

        rbtshell.setBackground(new java.awt.Color(0, 0, 0));
        rbtshell.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        rbtshell.setForeground(new java.awt.Color(0, 255, 51));
        rbtshell.setText("SHELL");
        rbtshell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtshellActionPerformed(evt);
            }
        });

        rtbquic.setBackground(new java.awt.Color(0, 0, 0));
        rtbquic.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        rtbquic.setForeground(new java.awt.Color(51, 255, 0));
        rtbquic.setText("QUICK SORT");
        rtbquic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtbquicActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("ALGORITMO");

        txtresultado.setBackground(new java.awt.Color(0, 0, 0));
        txtresultado.setColumns(20);
        txtresultado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtresultado.setForeground(new java.awt.Color(51, 255, 51));
        txtresultado.setRows(5);
        jScrollPane2.setViewportView(txtresultado);

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("RESULTADO");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("____________________________________________________________________");

        javax.swing.GroupLayout pre2Layout = new javax.swing.GroupLayout(pre2);
        pre2.setLayout(pre2Layout);
        pre2Layout.setHorizontalGroup(
            pre2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pre2Layout.createSequentialGroup()
                .addGroup(pre2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pre2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pre2Layout.createSequentialGroup()
                        .addGroup(pre2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pre2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(pre2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pre2Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(rbtshell, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(61, 61, 61)
                                        .addComponent(rtbquic, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pre2Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtarchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pre2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pre2Layout.setVerticalGroup(
            pre2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pre2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pre2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtarchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(pre2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtshell)
                    .addComponent(rtbquic))
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2)
                .addGap(14, 14, 14))
        );

        jPanel6.setBackground(java.awt.SystemColor.activeCaption);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("DATOS ORIGINALES");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("DATOS ORDENADOS");

        tablaoriginal.setBackground(new java.awt.Color(0, 0, 0));
        tablaoriginal.setForeground(new java.awt.Color(0, 255, 0));
        tablaoriginal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "DATOS"
            }
        ));
        jScrollPane3.setViewportView(tablaoriginal);

        tablaordenado.setBackground(new java.awt.Color(0, 0, 0));
        tablaordenado.setForeground(new java.awt.Color(0, 255, 0));
        tablaordenado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "DATOS"
            }
        ));
        jScrollPane1.setViewportView(tablaordenado);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 52, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pre1Layout = new javax.swing.GroupLayout(pre1);
        pre1.setLayout(pre1Layout);
        pre1Layout.setHorizontalGroup(
            pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pre1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pre1Layout.createSequentialGroup()
                        .addComponent(pre2, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pre1Layout.setVerticalGroup(
            pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pre1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pre2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        getContentPane().add(pre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncargarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncargarMouseEntered
        // TODO add your handling code here:
        btncargar.setBorder(
            BorderFactory.createLineBorder(
                new Color(0,0,0),2
            )
        );
        btncargar.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_btncargarMouseEntered

    private void btncargarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncargarMouseExited
        // TODO add your handling code here:
        btncargar.setBorder(null);
    }//GEN-LAST:event_btncargarMouseExited

    private void btncargarbtnpregun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncargarbtnpregun1ActionPerformed
        // TODO add your handling code here:
          JFileChooser fc = new JFileChooser();

    int opcion = fc.showOpenDialog(this);

    if (opcion == JFileChooser.APPROVE_OPTION) {

        File archivo = fc.getSelectedFile();

        txtarchivo.setText(archivo.getAbsolutePath());

        try {

            Txt_utp.cargarArchivo(
                    archivo.getAbsolutePath(),
                    lista
            );

            DefaultTableModel modelo =
                    (DefaultTableModel) tablaoriginal.getModel();

            modelo.setRowCount(0);

            for (Numero n : lista.getLista()) {

                modelo.addRow(new Object[]{
                    n.getValor()
                });

            }

            JOptionPane.showMessageDialog(
                    this,
                    "Archivo cargado correctamente."
            );

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error al cargar el archivo.\n" + e.getMessage()
            );

        }

    }
   
      
    }//GEN-LAST:event_btncargarbtnpregun1ActionPerformed

    private void btnresolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnresolverMouseEntered
        // TODO add your handling code here:
        btnresolver.setBorder(
            BorderFactory.createLineBorder(
                new Color(0,0,0),2
            )
        );
        btnresolver.setBackground(new Color(45,45,45));
    }//GEN-LAST:event_btnresolverMouseEntered

    private void btnresolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnresolverMouseExited
        // TODO add your handling code here:
        btnresolver.setBorder(null);
    }//GEN-LAST:event_btnresolverMouseExited

    private void btnresolverbtnpregun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresolverbtnpregun1ActionPerformed
        // TODO add your handling code here:
       if (lista.tamaño() == 0) {
        JOptionPane.showMessageDialog(this,
                "Primero cargue un archivo.");
        return;
    }

    DefaultTableModel modelo =
            (DefaultTableModel) tablaordenado.getModel();

    modelo.setRowCount(0);

    long inicio = System.nanoTime();

    if (rbtshell.isSelected()) {

        Shellsort shell = new Shellsort();

        shell.ordenar(lista.getLista());

        long fin = System.nanoTime();

        for (Numero n : lista.getLista()) {

            modelo.addRow(new Object[]{
                n.getValor()
            });

        }

        txtresultado.setText(
        "ALGORITMO: SHELL SORT\n\n" +
        "Tiempo: " + (fin - inicio) + " ns\n" +
        "Comparaciones: " + shell.getComparaciones() + "\n" +
        "Intercambios: " + shell.getIntercambios() + "\n\n" +
        "Complejidad:\n" +
        "Mejor caso: O(n log n)\n" +
        "Caso promedio: Depende de la secuencia\n" +
        "Peor caso: O(n²)"
);

    } else if (rtbquic.isSelected()) {

        Quicksort quick = new Quicksort();

        quick.ordenar(lista.getLista());

        long fin = System.nanoTime();

        for (Numero n : lista.getLista()) {

            modelo.addRow(new Object[]{
                n.getValor()
            });

        }

       txtresultado.setText(
        "ALGORITMO: QUICK SORT\n\n" +
        "Tiempo: " + (fin - inicio) + " ns\n" +
        "Comparaciones: " + quick.getComparaciones() + "\n" +
        "Intercambios: " + quick.getIntercambios() + "\n\n" +
        "Complejidad:\n" +
        "Mejor caso: O(n log n)\n" +
        "Promedio: O(n log n)\n" +
        "Peor caso: O(n²)"
);

    } else {

        JOptionPane.showMessageDialog(this,
                "Seleccione un algoritmo.");

    }

       
         

    }//GEN-LAST:event_btnresolverbtnpregun1ActionPerformed

    private void btnmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenuMouseEntered
        // TODO add your handling code here:
        btnmenu.setBorder(null);
    }//GEN-LAST:event_btnmenuMouseEntered

    private void btnmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenuMouseExited
        // TODO add your handling code here:
        btnmenu.setBorder(
            BorderFactory.createLineBorder(
                new Color(0,0,0),2
            )
        );
        btnmenu.setBackground(new Color(45,45,45));
    }//GEN-LAST:event_btnmenuMouseExited

    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
        // TODO add your handling code here:
        Menu m = new Menu();
        m.setVisible(true);
        m.setLocationRelativeTo(null);
        this.dispose();

    }//GEN-LAST:event_btnmenuActionPerformed

    private void btnlimpiar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlimpiar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlimpiar1MouseEntered

    private void btnlimpiar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlimpiar1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlimpiar1MouseExited

    private void btnlimpiar1btnpregun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiar1btnpregun1ActionPerformed
        // TODO add your handling code here:
        txtarchivo.setText("");

    // Si tienes JTextArea de resultados
    // txtresultado.setText("");

    // Limpiar tabla original
    DefaultTableModel modeloOriginal =
            (DefaultTableModel) tablaoriginal.getModel();
    modeloOriginal.setRowCount(0);

    // Limpiar tabla Shell
    DefaultTableModel modeloShell =
            (DefaultTableModel) tablaordenado.getModel();
    modeloShell.setRowCount(0);

   

    // Limpiar listas
    lista.getLista().clear();

   txtresultado.setText("");

    JOptionPane.showMessageDialog(
            this,
            "Datos limpiados correctamente."
    );
    }//GEN-LAST:event_btnlimpiar1btnpregun1ActionPerformed

    private void rbtshellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtshellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtshellActionPerformed

    private void rtbquicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtbquicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rtbquicActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncargar;
    private javax.swing.JButton btnlimpiar1;
    private javax.swing.JButton btnmenu;
    private javax.swing.JButton btnresolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel pre1;
    private javax.swing.JPanel pre2;
    private javax.swing.JRadioButton rbtshell;
    private javax.swing.JRadioButton rtbquic;
    private javax.swing.JTable tablaordenado;
    private javax.swing.JTable tablaoriginal;
    private javax.swing.JTextField txtarchivo;
    private javax.swing.JTextArea txtresultado;
    // End of variables declaration//GEN-END:variables
}
