/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISUAL;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.Image;
import java.awt.Color;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.table.DefaultTableModel;
import logica.grafos15_1;

/**
 *
 * @author darwi
 */
public class PREGUNTA15_1 extends javax.swing.JFrame {

    /**
     * Creates new form PRINCIPAL
     */
    public PREGUNTA15_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pre1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btncargar = new javax.swing.JButton();
        btnresolver = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        btnmenu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablagrados = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtresultado = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblimagen = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pre1.setBackground(new java.awt.Color(0, 0, 18));
        pre1.setForeground(new java.awt.Color(102, 102, 102));
        pre1.setPreferredSize(new java.awt.Dimension(945, 670));

        jPanel1.setBackground(new java.awt.Color(0, 40, 57));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncargar.setBackground(new java.awt.Color(0, 0, 0));
        btncargar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btncargar.setForeground(new java.awt.Color(51, 255, 51));
        btncargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/CARPETA_1.png"))); // NOI18N
        btncargar.setText("CARGAR");
        btncargar.setAutoscrolls(true);
        btncargar.setContentAreaFilled(false);
        btncargar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncargar.setDoubleBuffered(true);
        btncargar.setFocusCycleRoot(true);
        btncargar.setFocusPainted(false);
        btncargar.setFocusable(false);
        btncargar.setVerifyInputWhenFocusTarget(false);
        btncargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncargarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncargarMouseExited(evt);
            }
        });
        btncargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncargarbtnpregun1ActionPerformed(evt);
            }
        });
        jPanel1.add(btncargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 163, 50));

        btnresolver.setBackground(new java.awt.Color(0, 0, 0));
        btnresolver.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnresolver.setForeground(new java.awt.Color(0, 255, 51));
        btnresolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/PLAY_COLOR.png"))); // NOI18N
        btnresolver.setText("RESOLVER ");
        btnresolver.setAutoscrolls(true);
        btnresolver.setContentAreaFilled(false);
        btnresolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnresolver.setDefaultCapable(false);
        btnresolver.setFocusPainted(false);
        btnresolver.setFocusable(false);
        btnresolver.setRequestFocusEnabled(false);
        btnresolver.setRolloverEnabled(false);
        btnresolver.setVerifyInputWhenFocusTarget(false);
        btnresolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnresolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnresolverMouseExited(evt);
            }
        });
        btnresolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresolverbtnpregun1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnresolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 200, 50));

        btnlimpiar.setBackground(new java.awt.Color(0, 0, 0));
        btnlimpiar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnlimpiar.setForeground(new java.awt.Color(51, 255, 51));
        btnlimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/LIMPIAR_ORIGINAL_COLOR.png"))); // NOI18N
        btnlimpiar.setText("LIMPIAR");
        btnlimpiar.setAutoscrolls(true);
        btnlimpiar.setContentAreaFilled(false);
        btnlimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlimpiar.setDoubleBuffered(true);
        btnlimpiar.setFocusCycleRoot(true);
        btnlimpiar.setFocusPainted(false);
        btnlimpiar.setFocusable(false);
        btnlimpiar.setVerifyInputWhenFocusTarget(false);
        btnlimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlimpiarMouseExited(evt);
            }
        });
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarbtnpregun1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnlimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 190, 50));

        btnmenu.setBackground(new java.awt.Color(0, 0, 0));
        btnmenu.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        btnmenu.setForeground(new java.awt.Color(0, 255, 0));
        btnmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/MENUU_COLORR.png"))); // NOI18N
        btnmenu.setText("MENU");
        btnmenu.setAutoscrolls(true);
        btnmenu.setContentAreaFilled(false);
        btnmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmenu.setDoubleBuffered(true);
        btnmenu.setFocusCycleRoot(true);
        btnmenu.setFocusPainted(false);
        btnmenu.setFocusable(false);
        btnmenu.setVerifyInputWhenFocusTarget(false);
        btnmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnmenuMouseExited(evt);
            }
        });
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 170, 50));

        jPanel2.setBackground(java.awt.SystemColor.activeCaption);
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        tablagrados.setBackground(new java.awt.Color(0, 0, 0));
        tablagrados.setForeground(new java.awt.Color(0, 255, 0));
        tablagrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "NODOS", "GRADOS"
            }
        ));
        jScrollPane1.setViewportView(tablagrados);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(java.awt.SystemColor.activeCaption);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setForeground(java.awt.SystemColor.activeCaptionText);
        jLabel3.setText("RESULTADO");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(java.awt.SystemColor.activeCaptionText);
        jLabel4.setText("BUSCAR");

        txtresultado.setBackground(new java.awt.Color(0, 0, 0));
        txtresultado.setColumns(20);
        txtresultado.setForeground(new java.awt.Color(51, 255, 51));
        txtresultado.setRows(5);
        jScrollPane2.setViewportView(txtresultado);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(534, 534, 534)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel4.setBackground(java.awt.SystemColor.activeCaption);

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel6.setForeground(java.awt.SystemColor.activeCaptionText);
        jLabel6.setText("IMAGEN");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("GRAFOS NO DIRIGIDOS ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pre1Layout = new javax.swing.GroupLayout(pre1);
        pre1.setLayout(pre1Layout);
        pre1Layout.setHorizontalGroup(
            pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pre1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE)
                    .addGroup(pre1Layout.createSequentialGroup()
                        .addGroup(pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pre1Layout.setVerticalGroup(
            pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pre1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pre1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109))
        );

        getContentPane().add(pre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncargarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncargarMouseEntered
        // TODO add your handling code here:
        btncargar.setBorder(
            BorderFactory.createLineBorder(
                new Color(0,0,0),2
            )
        );
        btncargar.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_btncargarMouseEntered

    private void btncargarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncargarMouseExited
        // TODO add your handling code here:
        btncargar.setBorder(null);
    }//GEN-LAST:event_btncargarMouseExited

    private void btncargarbtnpregun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncargarbtnpregun1ActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();

    FileNameExtensionFilter filtro =
            new FileNameExtensionFilter(
                    "Imágenes", "jpg", "jpeg", "png");

    fc.setFileFilter(filtro);

    int opcion = fc.showOpenDialog(this);

    if (opcion == JFileChooser.APPROVE_OPTION) {

        File archivo = fc.getSelectedFile();

        txtresultado.setText(archivo.getAbsolutePath());

        ImageIcon imagen = new ImageIcon(archivo.getAbsolutePath());

        Image img = imagen.getImage().getScaledInstance(
                lblimagen.getWidth(),
                lblimagen.getHeight(),
                Image.SCALE_SMOOTH);

        lblimagen.setIcon(new ImageIcon(img));

    }
      
    }//GEN-LAST:event_btncargarbtnpregun1ActionPerformed

    private void btnresolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnresolverMouseEntered
        // TODO add your handling code here:
        btnresolver.setBorder(
            BorderFactory.createLineBorder(
                new Color(0,0,0),2
            )
        );
        btnresolver.setBackground(new Color(45,45,45));
    }//GEN-LAST:event_btnresolverMouseEntered

    private void btnresolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnresolverMouseExited
        // TODO add your handling code here:
        btnresolver.setBorder(null);
    }//GEN-LAST:event_btnresolverMouseExited

    private void btnresolverbtnpregun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresolverbtnpregun1ActionPerformed
        // TODO add your handling code here:
          grafos15_1 resolver = new grafos15_1();

    // Mostrar V y A
    txtresultado.setText("");

    txtresultado.append("CONJUNTO DE VÉRTICES\n");
    txtresultado.append(resolver.obtenerVertices());

    txtresultado.append("\n\n");

    txtresultado.append("CONJUNTO DE ARISTAS\n");
    txtresultado.append(resolver.obtenerAristas());

    txtresultado.append("\n\n");

    txtresultado.append("GRADO DE CADA NODO\n");

    DefaultTableModel modelo =
            (DefaultTableModel) tablagrados.getModel();

    modelo.setRowCount(0);

    Map<String, Integer> grados =
            resolver.obtenerGrados();

    for (Map.Entry<String, Integer> dato : grados.entrySet()) {

        modelo.addRow(new Object[]{
            dato.getKey(),
            dato.getValue()
        });

        txtresultado.append(
                "Grado(" + dato.getKey() + ") = "
                + dato.getValue() + "\n"
        );

    }

       
         

    }//GEN-LAST:event_btnresolverbtnpregun1ActionPerformed

    private void btnlimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlimpiarMouseEntered
        // TODO add your handling code here:
        btnlimpiar.setBorder(
            BorderFactory.createLineBorder(
                new Color(0,0,0),2
            )
        );
        btnlimpiar.setBackground(new Color(45,45,45));
    }//GEN-LAST:event_btnlimpiarMouseEntered

    private void btnlimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlimpiarMouseExited
        // TODO add your handling code here:
        btnlimpiar.setBorder(null);
    }//GEN-LAST:event_btnlimpiarMouseExited

    private void btnlimpiarbtnpregun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarbtnpregun1ActionPerformed
        // TODO add your handling code here:
        lblimagen.setIcon(null);

txtresultado.setText("");

DefaultTableModel modelo =
        (DefaultTableModel) tablagrados.getModel();

modelo.setRowCount(0);
    }//GEN-LAST:event_btnlimpiarbtnpregun1ActionPerformed

    private void btnmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenuMouseEntered
        // TODO add your handling code here:
        btnmenu.setBorder(null);
    }//GEN-LAST:event_btnmenuMouseEntered

    private void btnmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenuMouseExited
        // TODO add your handling code here:
        btnmenu.setBorder(
            BorderFactory.createLineBorder(
                new Color(0,0,0),2
            )
        );
        btnmenu.setBackground(new Color(45,45,45));
    }//GEN-LAST:event_btnmenuMouseExited

    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
        // TODO add your handling code here:
        Menu m = new Menu();
        m.setVisible(true);
        m.setLocationRelativeTo(null);
        this.dispose();

    }//GEN-LAST:event_btnmenuActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncargar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnmenu;
    private javax.swing.JButton btnresolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblimagen;
    private javax.swing.JPanel pre1;
    private javax.swing.JTable tablagrados;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextArea txtresultado;
    // End of variables declaration//GEN-END:variables
}
