/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISUAL;

import Logica.Busqueda_binaria;
import Logica.Busqueda_lineal;
import Logica.ListaNumeros;
import Logica.Numero;
import Logica.Txt_utp;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author darwi
 */
public class PREGUNTA2 extends javax.swing.JFrame {
private ListaNumeros lista = new ListaNumeros();
private Txt_utp txt = new Txt_utp();
    /**
     * Creates new form PREGUNTAA_1
     */
    public PREGUNTA2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pre1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btncargar = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        btnmenu = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtarchivo = new javax.swing.JTextField();
        rbtlineal = new javax.swing.JRadioButton();
        rbtcomparar = new javax.swing.JRadioButton();
        rbtinaria = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablalineal = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablabinaria = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaordenada = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaoriginal1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pre1.setBackground(new java.awt.Color(0, 0, 18));
        pre1.setForeground(new java.awt.Color(102, 102, 102));
        pre1.setPreferredSize(new java.awt.Dimension(945, 670));

        jPanel1.setBackground(new java.awt.Color(0, 40, 57));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncargar.setBackground(new java.awt.Color(0, 0, 0));
        btncargar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btncargar.setForeground(new java.awt.Color(51, 255, 51));
        btncargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/CARPETA_1.png"))); // NOI18N
        btncargar.setText("CARGAR");
        btncargar.setAutoscrolls(true);
        btncargar.setContentAreaFilled(false);
        btncargar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btncargar.setDoubleBuffered(true);
        btncargar.setFocusCycleRoot(true);
        btncargar.setFocusPainted(false);
        btncargar.setFocusable(false);
        btncargar.setVerifyInputWhenFocusTarget(false);
        btncargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncargarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncargarMouseExited(evt);
            }
        });
        btncargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncargarbtnpregun1ActionPerformed(evt);
            }
        });
        jPanel1.add(btncargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 163, 46));

        btnbuscar.setBackground(new java.awt.Color(0, 0, 0));
        btnbuscar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnbuscar.setForeground(new java.awt.Color(0, 255, 51));
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/BUSCAR_CLARRO.png"))); // NOI18N
        btnbuscar.setText("BUSCAR");
        btnbuscar.setAutoscrolls(true);
        btnbuscar.setContentAreaFilled(false);
        btnbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnbuscar.setDefaultCapable(false);
        btnbuscar.setFocusPainted(false);
        btnbuscar.setFocusable(false);
        btnbuscar.setRequestFocusEnabled(false);
        btnbuscar.setRolloverEnabled(false);
        btnbuscar.setVerifyInputWhenFocusTarget(false);
        btnbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnbuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnbuscarMouseExited(evt);
            }
        });
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarbtnpregun1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 200, 46));

        btnlimpiar.setBackground(new java.awt.Color(0, 0, 0));
        btnlimpiar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnlimpiar.setForeground(new java.awt.Color(51, 255, 51));
        btnlimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/LIMPIAR_ORIGINAL_COLOR.png"))); // NOI18N
        btnlimpiar.setText("LIMPIAR");
        btnlimpiar.setAutoscrolls(true);
        btnlimpiar.setContentAreaFilled(false);
        btnlimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnlimpiar.setDoubleBuffered(true);
        btnlimpiar.setFocusCycleRoot(true);
        btnlimpiar.setFocusPainted(false);
        btnlimpiar.setFocusable(false);
        btnlimpiar.setVerifyInputWhenFocusTarget(false);
        btnlimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlimpiarMouseExited(evt);
            }
        });
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarbtnpregun1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnlimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 190, 50));

        btnmenu.setBackground(new java.awt.Color(0, 0, 0));
        btnmenu.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnmenu.setForeground(new java.awt.Color(0, 255, 0));
        btnmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/MENUU_COLORR.png"))); // NOI18N
        btnmenu.setText("MENU");
        btnmenu.setAutoscrolls(true);
        btnmenu.setContentAreaFilled(false);
        btnmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnmenu.setDoubleBuffered(true);
        btnmenu.setFocusCycleRoot(true);
        btnmenu.setFocusPainted(false);
        btnmenu.setFocusable(false);
        btnmenu.setVerifyInputWhenFocusTarget(false);
        btnmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnmenuMouseExited(evt);
            }
        });
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, 170, 50));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setText("BÚSQUEDA LINEAL VS BINARIA ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jPanel2.setBackground(java.awt.SystemColor.activeCaption);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setText("ARCHIVO:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 111, 34));

        txtbuscar.setBackground(new java.awt.Color(0, 0, 0));
        txtbuscar.setForeground(new java.awt.Color(51, 255, 0));
        jPanel2.add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 140, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setText("BUSCAR:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 34));

        txtarchivo.setEditable(false);
        txtarchivo.setBackground(new java.awt.Color(0, 0, 0));
        txtarchivo.setForeground(new java.awt.Color(51, 255, 51));
        jPanel2.add(txtarchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 390, 30));

        rbtlineal.setBackground(new java.awt.Color(0, 0, 0));
        rbtlineal.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        rbtlineal.setForeground(java.awt.SystemColor.inactiveCaption);
        rbtlineal.setText("LINEAL");
        rbtlineal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtlinealActionPerformed(evt);
            }
        });
        jPanel2.add(rbtlineal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 129, -1));

        rbtcomparar.setBackground(new java.awt.Color(0, 0, 0));
        rbtcomparar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        rbtcomparar.setForeground(java.awt.SystemColor.inactiveCaption);
        rbtcomparar.setText("COMPARAR");
        rbtcomparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtcompararActionPerformed(evt);
            }
        });
        jPanel2.add(rbtcomparar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 129, -1));

        rbtinaria.setBackground(new java.awt.Color(0, 0, 0));
        rbtinaria.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        rbtinaria.setForeground(java.awt.SystemColor.inactiveCaption);
        rbtinaria.setText("BINARIA");
        rbtinaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtinariaActionPerformed(evt);
            }
        });
        jPanel2.add(rbtinaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 129, -1));

        jPanel3.setBackground(java.awt.SystemColor.activeCaption);

        tablalineal.setBackground(java.awt.SystemColor.activeCaptionText);
        tablalineal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablalineal.setForeground(new java.awt.Color(51, 255, 0));
        tablalineal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NUMERO", "ENCONTRADO", "POSICION", "COMPARACiON", "TIEMPO"
            }
        ));
        jScrollPane2.setViewportView(tablalineal);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel4.setBackground(java.awt.SystemColor.activeCaption);

        tablabinaria.setBackground(java.awt.SystemColor.activeCaptionText);
        tablabinaria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablabinaria.setForeground(new java.awt.Color(51, 255, 0));
        tablabinaria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NUMERO", "ENCONTRADO", "POSICION", "COMPARACION", "TIEMPO"
            }
        ));
        jScrollPane5.setViewportView(tablabinaria);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel5.setBackground(java.awt.SystemColor.activeCaption);
        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 0));
        jLabel5.setText("RESULTADO LINEAL");

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 255, 51));
        jLabel6.setText("RESULTADO BINARIA");

        jPanel6.setBackground(java.awt.SystemColor.activeCaption);

        tablaordenada.setBackground(java.awt.SystemColor.activeCaptionText);
        tablaordenada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablaordenada.setForeground(new java.awt.Color(51, 255, 51));
        tablaordenada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "DATOS ORDENADOS"
            }
        ));
        jScrollPane4.setViewportView(tablaordenada);

        tablaoriginal1.setBackground(java.awt.SystemColor.activeCaptionText);
        tablaoriginal1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablaoriginal1.setForeground(new java.awt.Color(51, 255, 51));
        tablaoriginal1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "DATOS ORIGINALES"
            }
        ));
        jScrollPane6.setViewportView(tablaoriginal1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pre1Layout = new javax.swing.GroupLayout(pre1);
        pre1.setLayout(pre1Layout);
        pre1Layout.setHorizontalGroup(
            pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pre1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1062, Short.MAX_VALUE)
                    .addGroup(pre1Layout.createSequentialGroup()
                        .addGroup(pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pre1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pre1Layout.setVerticalGroup(
            pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pre1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1074, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(pre1, javax.swing.GroupLayout.PREFERRED_SIZE, 1074, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(pre1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncargarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncargarMouseEntered
        // TODO add your handling code here:
        btncargar.setBorder(
            BorderFactory.createLineBorder(
                new Color(0,0,0),2
            )
        );
        btncargar.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_btncargarMouseEntered

    private void btncargarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncargarMouseExited
        // TODO add your handling code here:
        btncargar.setBorder(null);
    }//GEN-LAST:event_btncargarMouseExited

    private void btncargarbtnpregun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncargarbtnpregun1ActionPerformed
        // TODO add your handling code here:
JFileChooser fc = new JFileChooser();

    int opcion = fc.showOpenDialog(this);

    if (opcion == JFileChooser.APPROVE_OPTION) {

        File archivo = fc.getSelectedFile();

        txtarchivo.setText(archivo.getAbsolutePath());

        try {

            Txt_utp.cargarArchivo(
                    archivo.getAbsolutePath(),
                    lista
            );

          

            DefaultTableModel modeloOriginal =
                    (DefaultTableModel) tablaoriginal1.getModel();

            modeloOriginal.setRowCount(0);

            for (Numero n : lista.getLista()) {

                modeloOriginal.addRow(new Object[]{
                    n.getValor()
                });

            }


            ArrayList<Numero> listaOrdenada =
                    new ArrayList<>(lista.getLista());

            Collections.sort(listaOrdenada,
                    Comparator.comparingInt(Numero::getValor));

            DefaultTableModel modeloOrdenado =
                    (DefaultTableModel) tablaordenada.getModel();

            modeloOrdenado.setRowCount(0);

            for (Numero n : listaOrdenada) {

                modeloOrdenado.addRow(new Object[]{
                    n.getValor()
                });

            }

            JOptionPane.showMessageDialog(
                    this,
                    "Archivo cargado correctamente."
            );

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error al cargar el archivo.\n" + e.getMessage()
            );

        }

    }


    }//GEN-LAST:event_btncargarbtnpregun1ActionPerformed

    private void btnbuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscarMouseEntered
        // TODO add your handling code here:
        btnbuscar.setBorder(
            BorderFactory.createLineBorder(
                new Color(0,0,0),2
            )
        );
        btnbuscar.setBackground(new Color(45,45,45));
    }//GEN-LAST:event_btnbuscarMouseEntered

    private void btnbuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscarMouseExited
        btnbuscar.setBorder(null);
    }//GEN-LAST:event_btnbuscarMouseExited

    private void btnbuscarbtnpregun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarbtnpregun1ActionPerformed
        // TODO add your handling code here
         if (lista.getLista().isEmpty()) {

        JOptionPane.showMessageDialog(this,
                "Primero cargue un archivo.");
        return;

    }

    if (txtbuscar.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(this,
                "Ingrese el número a buscar.");
        return;

    }

    int numeroBuscar = Integer.parseInt(txtbuscar.getText());

   
   

    if (rbtlineal.isSelected()) {

        Busqueda_lineal lineal = new Busqueda_lineal();

        lineal.buscar(lista.getLista(), numeroBuscar);

        DefaultTableModel modelo =
                (DefaultTableModel) tablalineal.getModel();

        modelo.setRowCount(0);

        modelo.addRow(new Object[]{
            numeroBuscar,
            lineal.isEncontrado() ? "SI" : "NO",
            lineal.getPosicion(),
            lineal.getComparaciones(),
            lineal.getTiempo()
        });

    }

    else if (rbtinaria.isSelected()) {

        ArrayList<Numero> copia = new ArrayList<>(lista.getLista());

        Collections.sort(copia,
                Comparator.comparingInt(Numero::getValor));

        Busqueda_binaria binaria = new Busqueda_binaria();

        binaria.buscar(copia, numeroBuscar);

        DefaultTableModel modelo =
                (DefaultTableModel) tablabinaria.getModel();

        modelo.setRowCount(0);

        modelo.addRow(new Object[]{
            numeroBuscar,
            binaria.isEncontrado() ? "SI" : "NO",
            binaria.getPosicion(),
            binaria.getComparaciones(),
            binaria.getTiempo()
        });

    }

   
    else if (rbtcomparar.isSelected()) {

        Busqueda_lineal lineal = new Busqueda_lineal();

        lineal.buscar(lista.getLista(), numeroBuscar);

        ArrayList<Numero> copia = new ArrayList<>(lista.getLista());

        Collections.sort(copia,
                Comparator.comparingInt(Numero::getValor));

        Busqueda_binaria binaria = new Busqueda_binaria();

        binaria.buscar(copia, numeroBuscar);

        DefaultTableModel modeloL =
                (DefaultTableModel) tablalineal.getModel();

        DefaultTableModel modeloB =
                (DefaultTableModel) tablabinaria.getModel();

        modeloL.setRowCount(0);
        modeloB.setRowCount(0);

        modeloL.addRow(new Object[]{
            numeroBuscar,
            lineal.isEncontrado() ? "SI" : "NO",
            lineal.getPosicion(),
            lineal.getComparaciones(),
            lineal.getTiempo()
        });

        modeloB.addRow(new Object[]{
            numeroBuscar,
            binaria.isEncontrado() ? "SI" : "NO",
            binaria.getPosicion(),
            binaria.getComparaciones(),
            binaria.getTiempo()
        });

    }

    else {

        JOptionPane.showMessageDialog(this,
                "Seleccione un método de búsqueda.");

    }

   
    }//GEN-LAST:event_btnbuscarbtnpregun1ActionPerformed
    
    private void btnlimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlimpiarMouseEntered
        // TODO add your handling code here:
        btnlimpiar.setBorder(
            BorderFactory.createLineBorder(
                new Color(0,0,0),2
            )
        );
        btnlimpiar.setBackground(new Color(45,45,45));
    }//GEN-LAST:event_btnlimpiarMouseEntered

    private void btnlimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlimpiarMouseExited
        // TODO add your handling code here:
        btnlimpiar.setBorder(null);
    }//GEN-LAST:event_btnlimpiarMouseExited

    private void btnlimpiarbtnpregun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarbtnpregun1ActionPerformed
        txtarchivo.setText("");
    txtbuscar.setText("");

    DefaultTableModel modeloOriginal =
            (DefaultTableModel) tablaordenada.getModel();
    modeloOriginal.setRowCount(0);

    DefaultTableModel modeloOrdenada =
            (DefaultTableModel) tablaordenada.getModel();
    modeloOrdenada.setRowCount(0);

    DefaultTableModel modeloLineal =
            (DefaultTableModel) tablalineal.getModel();
    modeloLineal.setRowCount(0);

    DefaultTableModel modeloBinaria =
            (DefaultTableModel) tablabinaria.getModel();
    modeloBinaria.setRowCount(0);

   
    JOptionPane.showMessageDialog(
            this,
            "Datos limpiados correctamente."
    );
        
    }//GEN-LAST:event_btnlimpiarbtnpregun1ActionPerformed

    private void btnmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenuMouseEntered
        // TODO add your handling code here:
        btnmenu.setBorder(null);
    }//GEN-LAST:event_btnmenuMouseEntered

    private void btnmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenuMouseExited
        // TODO add your handling code here:
        btnmenu.setBorder(
            BorderFactory.createLineBorder(
                new Color(0,0,0),2
            )
        );
        btnmenu.setBackground(new Color(45,45,45));
    }//GEN-LAST:event_btnmenuMouseExited

    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
        // TODO add your handling code here:
        Menu m = new Menu();
        m.setVisible(true);
        m.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnmenuActionPerformed

    private void rbtlinealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtlinealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtlinealActionPerformed

    private void rbtcompararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtcompararActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtcompararActionPerformed

    private void rbtinariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtinariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtinariaActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncargar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnmenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel pre1;
    private javax.swing.JRadioButton rbtcomparar;
    private javax.swing.JRadioButton rbtinaria;
    private javax.swing.JRadioButton rbtlineal;
    private javax.swing.JTable tablabinaria;
    private javax.swing.JTable tablalineal;
    private javax.swing.JTable tablaordenada;
    private javax.swing.JTable tablaoriginal1;
    private javax.swing.JTextField txtarchivo;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
